name: App Services Keep Alive

on:
  schedule:
    - cron: "0 3,9,15,21 * * *"

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:

        # Runs for 5 hours 45 minutes
      - name: Malaysia Medicines Services (API, UI, Job) and Pharst Services (API) keep alive
        run: |
          x=0
          total_duration=$((5 * 3600 + 45 * 60))
          while [ $x -lt $total_duration ]; do
            curl https://devmalaysiamedicinesapi.azurewebsites.net/health
            curl https://devmalaysiamedicines.azurewebsites.net/health
            curl https://devmalaysiamedicinesjob.azurewebsites.net/health
            echo "Successful"
            curl https://malaysiamedicinesapi.azurewebsites.net/health
            curl https://malaysiamedicines.azurewebsites.net/health
            curl https://malaysiamedicinesjob.azurewebsites.net/health
            echo "Successful"
            curl https://devpharstapi.azurewebsites.net/health
            curl https://devpharstjob.azurewebsites.net/health
            echo "Successful"
            curl https://pharstapi.azurewebsites.net/health
            curl https://pharstjob.azurewebsites.net/health
            echo "Successful"
            sleep 900
            x=$((x + 900))
          done

      - name: GitHub Scheduled Actions Keepalive
        if: github.event_name == 'schedule'
        uses: liskin/gh-workflow-keepalive@v1
