name: Malaysia Medicines Product Details Scrape

on:
  schedule:
    - cron: "0 3,9,15,21 * * *"

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:

        # Runs for 5 hours 45 minutes
      - name: Dev and Prod Environment Product Details Scrape
        run: |
          x=0
          total_duration=$((5 * 3600 + 45 * 60))
          while [ $x -lt $total_duration ]; do
            curl https://devmalaysiamedicinesjob.azurewebsites.net/${{ secrets.PRODUCT_DETAIL_SCRAPE_ENDPOINT }}
            echo "Successful"
            curl https://malaysiamedicinesjob.azurewebsites.net/${{ secrets.PRODUCT_DETAIL_SCRAPE_ENDPOINT }}
            echo "Successful"
            sleep 500
            x=$((x + 500))
          done
