name: Malaysia Medicines Product Details Scrape

on:
  schedule:
    - cron: "0 3,9,15,21 * * *"

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:

      - name: Dev and Prod Environment Product Details Scrape
        run: |
          x=0
          total_duration=$((5 * 3600 + 30 * 60))
          while [ $x -lt $total_duration ]; do
            curl https://devmalaysiamedicinesjob.azurewebsites.net/${{ secrets.PRODUCT_DETAIL_SCRAPE_ENDPOINT }}
            curl https://malaysiamedicinesjob.azurewebsites.net/${{ secrets.PRODUCT_DETAIL_SCRAPE_ENDPOINT }}
            sleep 60
            x=$((x + 60))
          done

#      - name: Prod Dev Environment Product Details Scrape
#        run: |
#          curl https://malaysiamedicinesjob.azurewebsites.net/${{ secrets.PRODUCT_DETAIL_SCRAPE_ENDPOINT }}
