name: App Services Keep Alive

on:
  schedule:
    - cron: "*/18 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      actions: write
    steps:

      - name: Dev Services (API, UI, Job) keep alive
        run: |
          curl https://devmalaysiamedicinesapi.azurewebsites.net/health & \
          curl https://devmalaysiamedicines.azurewebsites.net/health & \
          curl https://devmalaysiamedicinesjob.azurewebsites.net/health

      - name: Prod Services (API, UI, Job) keep alive
        run: |
          curl https://malaysiamedicinesapi.azurewebsites.net/health & \
          curl https://malaysiamedicines.azurewebsites.net/health & \
          curl https://malaysiamedicinesjob.azurewebsites.net/health

      - name: GitHub Scheduled Actions Keepalive
        if: github.event_name == 'schedule'
        uses: liskin/gh-workflow-keepalive@v1
